### ISSUE TITLE
Needs retraining or not?

### ISSUE THREAD

**Issue by cl-love-mtt** [Jaluus/2DMatGMM#1]
I am also trying to find thin layers of graphene, if the light path or silicon conditions are different and I get a picture with a yellowish color, do I need to retrain the model?

**Comment by Jaluus** [comment]
Hey!

Yes, If your silicon has a different thickness, i.e. not 90nm, your camera has a different pixel sensitivity curve or you have a lamp with a different spectral profile, I would retrain the model with a few images.
About 3 to 5 per tickness should suffice.

If you are interested in optimizing the contrast of your graphene flakes, a good paper to read would be "[Making Graphene Visible](https://arxiv.org/abs/0705.0259)".

They test for 300nm SiO2 but our lab uses 90nm due to stronger and more stable contrast in the Red Green and Blue channel of the Camera.


If that works for you, I would love to hear how it went!

Best
Jan
